name: Transform
version: '0.1.0.0'
synopsis: Transformation from  DS KM JSON into the Form Engine format
category: Data
author: Marek Suchánek
maintainer: suchama4@fit.cvut.cz
license: Apache-2.0
homepage: https://github.com/DataStewardshipPortal/ds-wizard
extra-source-files:
- ChangeLog.md
other-extensions:
- OverloadedStrings
dependencies:
- base >=4.9 && <4.10
- text >=1.2 && <1.3
- aeson >=0.11 && <0.12
- bytestring >=0.10 && <0.11
- postgresql-simple
executables:
  Transform:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
